### PR TITLE
Only center the mouse if we get a mouse event with relative motion

### PR DESCRIPTION
**Pull request by slouken**
For more information, see the discussion in https://github.com/libsdl-org/SDL/issues/5569

Fixes https://github.com/DaemonEngine/Daemon/issues/600

### CODE REVIEW

**Comment by smcv** [comment]
This would probably allow #621 to be reverted, too.

**Comment by slipher** [comment]
@necessarily-equal claimed this will not fix it when I suggested the same. https://github.com/DaemonEngine/Daemon/pull/621#issuecomment-1086951636

**Comment by illwieckz** [comment]
Even if it may be not enough (are you sure?), maybe this is still wanted anyway? @slipher @necessarily-equal

**Comment by illwieckz** [comment]
```
<illwieckz> perturbed, do you thing something prevents that to be merged? https://github.com/DaemonEngine/Daemon/pull/624
<illwieckz> even if it's not 100% better, if it's already 50% better we may still merge it?
<perturbed> i don't have a problem
<afontain> I'd say we should merge it
<illwieckz> okok
```

**Comment by illwieckz** [comment]
Thank you @slouken! 👍️👍️👍️👍️👍️

**Comment by slouken** [comment]
You're welcome!

**Comment by necessarily-equal** [comment]
NixOS 22.05 updated to SDL2.0.20, I can confirm that this PR fixes the issue

**Pull request merged**
