### PR TITLE
WIP: computeLight: rewriting diffuse alpha channel looks suspicious

### PR DESCRIPTION
**Pull request by illwieckz**
Light accumulation was done on all color components including alpha channel, that can't be good.

---
This change is [Reviewable](https://reviewable.io/reviews/daemonengine/daemon/294)

### CODE REVIEW

**Comment by DolceTriade** [comment]
Does this fix anything?

**Comment by illwieckz** [comment]
No, I haven't seen something being broken because of that (or I was not aware of this), but that bug may be uncovered later when adding features or reorganizing code.

**Comment by slipher** [comment]
This is just debugging code, right?

**Comment by illwieckz** [comment]
Hmmm, I feel stupid, the alpha channel is not rewritten with light computation but with 1.0, which does not seems legit by the way, since 1.0 alpha channel is fully transparent.

And yes, it's debug code, I don't know how I managed to miss that. But anyway, setting a texture to be fully transparent to show the rgb channels seems wrong. For some reason, I'm not able to see the bug I expect.

This is the code _before_, this is not what I expect the code to render (and the glass displaying light color on borders if alpha channel is fully transparent?):

[debug alpha light](https://dl.illwieckz.net/b/daemon/bugs/debug-alpha-light/unvanquished_2020-02-26_134907_000.jpg)

This is the code _after_, which is what the code claims to do when there is no alpha channel rewrite:

[debug alpha light](https://dl.illwieckz.net/b/daemon/bugs/debug-alpha-light/unvanquished_2020-02-26_135148_000.jpg)

We may want to **not** blend the debug light color by setting it fully opaque (`0` alpha channel)

This is the code when there is alpha channel rewrite to 0.0 (fully opaque), so at least we know the alpha channel is read:

[debug alpha light](https://dl.illwieckz.net/b/daemon/bugs/debug-alpha-light/unvanquished_2020-02-26_142547_000.jpg)

So, what to do, keep the legacy behavior (set alpha channel to 1), keep the alpha channel unmodified?, set the alpha channel to 0 (fully opaque)?

Note that in later case, the light color is not displayed the same, maybe it's not what we want.

In all case I plan to merge the very first commit that reword stuff to make it more readable.

**Comment by VReaperV** [comment]
Alpha value 1.0 is opaque, not transparent. We would also get incorrect results on semi-transparent surfaces otherwise, because we don't want that affecting how light tiles are shown.

**Pull request closed without merging**
