### PR TITLE
Turn off precompiled headers by default as it is not handling recompilation properly

### PR DESCRIPTION
**Pull request by necessarily-equal**

### CODE REVIEW

**Comment by slipher** [comment]
Proofs? How can you reproduce? I've never had such issues.

**Comment by necessarily-equal** [comment]
Here's some example steps:

1. Build everything once
2. Remove half of daemon/src/common/Cvar.h in a way that the file 
compiles to a precompiled header, but everything else would be missing 
things from that file
3. Notice how it still builds
4. Notice that if you `make clean` then build again, it fails.

https://github.com/DaemonEngine/Daemon/issues/398 suggests that you are 
not using precompiled headers, which may be why you didn't notice yet.

After some time of wondering, I've got into an habbit of running `find 
~/unv/Unvanquished -name '*.h.gch' -delete` and modifying the file I 
changed (ex Math.h). Freem apparently has a similar command on his 
history, from what he said on IRC. So we are two to have noticed the 
problem independently.

**Comment by slipher** [comment]
Need more details like which OS, compiler, and CMake generator (build system) you are using.

I use precompiled headers most of the time and have built on all of our supported operating systems.

**Comment by necessarily-equal** [comment]
I'm building on Linux with GCC, ninja cmake backend, `cmake -D'BUILD_GAME_NACL=OFF' -D'BUILD_GAME_NACL_NEXE=OFF' -D'BUILD_GAME_NATIVE_EXE=OFF' -D'BUILD_GAME_NATIVE_DLL=ON' -GNinja -DCMAKE_BUILD_TYPE=Debug -Bbuild`. Hopefully this should be enough to reproduce

**Comment by slipher** [comment]
OK, I was able to reproduce. The problem is Ninja-specific. Maybe Ninja fails to automatically detect header dependencies for the PCH.

You can change the line that says `if (APPLE)` to also check if CMAKE_GENERATOR or whatever is equal Ninja.

**Comment by slipher** [comment]
https://cmake.org/cmake/help/latest/command/add_custom_command.html 

> Note that the IMPLICIT_DEPENDS option is currently supported only for Makefile generators and will be ignored by other generators.

That's the problem.

**Comment by illwieckz** [comment]
I implemented per-generator PCH disablement instead:

- #610

**Pull request closed without merging**
