### PR TITLE
Enable OpenGL error checking

### PR DESCRIPTION
**Pull request by slipher**
Also fix the existing errors which arise on my machine.

### CODE REVIEW

**Review by illwieckz — APPROVED** [review]
LGTM.

**Comment by illwieckz** [comment]
Now I see it is still fatal there: https://github.com/DaemonEngine/Daemon/blob/6b94e2e890f893afdc55b7f70bd58cb39f3cafcd/src/engine/renderer/tr_cmds.cpp#L863

**Comment by illwieckz** [comment]
If I replace all that custom code with:

```c++
	// check for errors
	if ( !r_ignoreGLErrors->integer )
	{
		R_SyncRenderThread();

		GL_CheckErrors();
	}
```

Now I don't get the error in `RE_BeginFrame`… :confused:

**Comment by slipher** [comment]
Thanks for spotting the duplicated code in RE_BeginFrame.  You didn't enable `r_smp` did you? If so, definitely turn it off while debugging. The error checking would be entirely disabled by the `smpActive` condition.

**Comment by illwieckz** [comment]
Ah yes `r_smp` is enabled.

**Pull request merged**
