### PR TITLE
appveyor: use Visual Studio 2019 and do 32-bit and 64-bit build

### PR DESCRIPTION
**Pull request by illwieckz**
use Visual Studio 2019 and do 32-bit and 64-bit build

### CODE REVIEW

**Comment by illwieckz** [comment]
lol, appveyor build worked, but travis failed because what looks to be a cache proxy just went offline while building…

**Comment by illwieckz** [comment]
It's all green now, but is the test significant?

**Comment by slipher** [comment]
Seems like an *anti*-cargo cult commit to me, as it deletes the `matrix` stuff which did nothing for us on account of there being only one build configuration :)

Are the Travis builds also 64-bit? I think it makes sense to have at least one 32-bit build somewhere, since we still supposedly support 32-bit Windows (although maybe we should stop?)

**Comment by illwieckz** [comment]
OK, it now tests both 32-bit and 64-bit platform build. Note that it does not use NMake generator but Visual Studio one. We may add a test for NMake (or Ninja, or…) if we think we really have to test those generators but in this case we would just test the platform that works and don't worry about any cross-platform build, as we would already know the platform works. We may also test older visual studio or other compilers if available, but for same reason, testing only one platform with others compilers would be enough.

**Comment by illwieckz** [comment]
Note: MSYS2 is available on the selected appveyor VM.

**Comment by illwieckz** [comment]
also, we may use MSYS2 shell to run [git-checkout-modules](https://gitlab.com/illwieckz/git-checkout-modules/) to sync branches.

**Pull request merged**
