### PR TITLE
renderer: missing break in shadowing code and other things

### PR DESCRIPTION
**Pull request by illwieckz**
It was missing in 1872b92274fbd9533e622633c56a515a4ff899c0 from:

- https://github.com/DaemonEngine/Daemon/pull/1045

### CODE REVIEW

**Comment by illwieckz** [comment]
I also added a fix for an inverted test.

**Comment by illwieckz** [comment]
I also added a fix for a logic change I mistakenly introduced.

I don't know if the original logic was right or wrong, but my previous patch changed the way it behaved.

**Comment by illwieckz** [comment]
I also added a commit to unify the wording of different functions doing similar things, it makes easier for the mind to spot the patterns.

**Comment by slipher** [comment]
LGTM

**Pull request merged**
