### PR TITLE
use explicit wording for reading cvar value

### PR DESCRIPTION
**Pull request by illwieckz**
hOw DiD wE mIsSeD tHaT fOr So lOnG? 🤔️

### CODE REVIEW

**Review by DolceTriade — COMMENTED** [review]
I think this code works fine...

https://github.com/DaemonEngine/Daemon/blob/895cb2c071ca4c0ed69f42e77c147a1d70d3183d/src/common/Cvar.h#L123

Means that `*` is overloaded to call `Get()`

**Comment by illwieckz** [comment]
> I think this code works fine...
> 
> https://github.com/DaemonEngine/Daemon/blob/895cb2c071ca4c0ed69f42e77c147a1d70d3183d/src/common/Cvar.h#L123
> 
> Means that `*` is overloaded to call `Get()`

Ah… Well, I prefer explicit code. 🤷‍♀️️

**Comment by illwieckz** [comment]
I renamed the commit `renderer: use explicit wording for reading cvar value`.

**Comment by slipher** [comment]
Should we nuke `operator*`?

**Comment by illwieckz** [comment]
> Should we nuke `operator*`?

I was going to ask the same. I don't want to have to guess the behavior of `*ptr` knowing it may differ according to the object type. It seems to just add extra mental load only to save on characters and allowing some kind of obfsucated code golf…

So if someone nukes it, I will approve…

**Comment by illwieckz** [comment]
I added a commit to NUKE the confusing `*cvar` syntax, it was used nowhere else.

**Comment by slipher** [comment]
LGTM

**Pull request merged**
