### PR TITLE
Fix curl error message

### PR DESCRIPTION
**Pull request by necessarily-equal**

### CODE REVIEW

**Comment by DolceTriade** [comment]
Seems non-critical to push to 0.54

**Comment by necessarily-equal** [comment]
I think I can do without, but on the other hand troubleshooting download issues is quite annoying because you HAVE TO make a nacl build. I think having proper error reporting can help a bit driving things forward if the binaries are not ready yet.

This change shouldn't risk inducing any breakage.

**Comment by necessarily-equal** [comment]
see https://github.com/Unvanquished/Unvanquished/issues/1981 for an example of how this hinders debugging

**Comment by slipher** [comment]
LGTM

**Review by DolceTriade — APPROVED** [review]

**Comment by necessarily-equal** [comment]
Thanks, you can merge it

**Pull request merged**
