### PR TITLE
Disable the clang errors on 'this' lambda captures.

### PR DESCRIPTION
**Pull request by slipher**

### CODE REVIEW

**Comment by DolceTriade** [comment]
I kinda feel like we should remove the unnecessary captures...

**Comment by slipher** [comment]
> I kinda feel like we should remove the unnecessary captures...

Are you volunteering? :stuck_out_tongue:

**Comment by DolceTriade** [comment]
Eventually.

**Comment by slipher** [comment]
Well I am just going to merge it now so we can use the CI.

**Pull request merged**
