### PR TITLE
tr_shader: do not detect heightmap in normalmap alpha channel, unless asked to, fix #375

### LINKED ISSUE #375: Bad normal map channel detection, seems to be related to missing ARB_texture_compression_rgtc
I noticed multiple bugs, some being regressions, on Nvidia Geforce 6000 and Geforce 7000 series. Those cards do not work with nouveau (`ARB_framebuffer_object` is missing and that's a requirement to run the game) but those card work with Nvidia 204 driver.

Nvida 304 driver is in really bad shape for Geforce 6000 series (most of them will just crash while the kernel complains they have `fallen off the buse`) but I haven't experienced such issue with a Geforce 7000 one.

Both Geforce 6000 and Geforce 7000 experience the bugs I've noticed.

While looking for the cause of the bug, I noticed this in `daemon.log`:

```
...GL_ARB_texture_compression_rgtc not found
```

Over the 40+ cards [that were tested](https://wiki.unvanquished.net/wiki/GPU_compatibility_matrix), no other one reproduces the bug, but also no one misses that extension. In fact the only other GPUs known to miss that extensions are the ones from the R300 series by ATI and they are experiencing another bug that prevent maps to load at all (see #345) so that other bug is likely to hide on ATI side the one I disscuss in this thread.

What I noticed is while the engine tells this extension is missing, the engine also prints wrong things in logs:

```
Debug: found heightmap embedded in normalmap 'textures/shared_pk02_src/floor12_n'
Debug: found heightmap embedded in normalmap 'textures/shared_pk02_src/floor12_n'
Debug: found heightmap embedded in normalmap 'textures/shared_pk02_src/floor09_n'
Debug: found heightmap embedded in normalmap 'textures/shared_pk02_src/floor06_n'
Debug: found heightmap embedded in normalmap 'textures/shared_pk02_src/floor05_n'
Debug: found heightmap embedded in normalmap 'textures/shared_pk02_src/floor04_n'
Debug: found heightmap embedded in normalmap 'textures/shared_pk02_src/floor03_n'
Debug: found heightmap embedded in normalmap 'textures/shared_pk02_src/floor01_n'
```

The wrong thing in those logs is that those textures do not ship height map in normal map file.
When an height map is shipped in a normal map file, the height map is stored in alpha channel, this is not the case here.

We have to detect if the height map is stored in alpha channel for two reasons:

- to use the height map
- to properly read the normal map

So if either height mapping or normal mapping is enabled, we have to detect if the normal map ships an height map.

We need to properly read the normal map when height mapping is disabled because we use a well know technique that is able to reconstruct the normal map from weird formats and in this case, some of the values is stored in alpha channel for optimization purpose (see [this snippet in glsl code](https://github.com/DaemonEngine/Daemon/blob/6b94e2e890f893afdc55b7f70bd58cb39f3cafcd/src/engine/renderer/glsl_source/reliefMapping_fp.glsl#L50-L77). See also [that comment](https://github.com/DaemonEngine/Daemon/issues/183#issuecomment-473691252) by @cmf028 who explains things well.  The code is written in a way that when a normal map does not ship height map in alpha channel, either storing XYZ in RGB or XYZ in RGA will produce the same result thanks to the compute producing the same result if A is default value for no alpha channel (fully opaque, one). But the engine must not attempt to reconstruct Z from alpha channel value when the normal map ships an height map or the compute would be wrong.

While the internal format (here CRN) stores the data in alpha channel for optimization purpose, the engine usually don't consider the file to be an RGBA file but an RGB one (only the GLSL code will know how to pick properly the required channels), then it's possible for the engine to know if the file embeds an height map or not. If there is three components, there is no height map even if there is some data hidden in alpha channel, if there is four components, there is an height map in alpha channel.

It looks like the two same logs occurs on the same cards. From all the cards tested at this point, only the Nvidia Geforce 6150LE, 6600 Silencer, 7500LE (both Curie hardware running on 304 drivers), ATI X300, X550HM and X1050 (both R300 hardware running on Mesa r300 driver) both report a missing `texture_compression_rgtc` and a wrong detection of an height map in normal map alpha channel while it's another RGA format instead.

### PR DESCRIPTION
**Pull request by illwieckz**
With this PR,

- `normalMap` material keyword loads a file and assume it's a normal map without height map in alpha channel (even if the engine believes there is an alpha channel because of a format being wrongly guessed on missing GL extension, see #375).
- `normalHeightMap` material keyword loads a file it's a normal map with an height map in alpha channel.

This code also introduces an internal `ParseNormalMapDetectHeightMap` function that attempts to detect an alpha channel and declare it's an heightmap. There is no material keyword for that and it must not be implemented as a keyword.

This internal function is only purposed to be used by compatibility code like the Darkplaces compatibility mode. Darkplaces-based games being known to not use formats that would break on detection, it's seems to be safe to use this detection function for their assets.

### CODE REVIEW

**Comment by illwieckz** [comment]
@slipher do you have any remark on it? I would appreciate some remark on pointer wizardry to keep an unmodified copy of `**text` if there is a better implementation possible.

**Comment by slipher** [comment]
I suggest as follows. Notes:

- DoDebugCode is used to execute the code only if the log level is `debug`. 
- `char buffer[1024] = "";` requires the entire buffer to be zeroed.

```cpp
	const char* initialText = *text;

	ParseNormalMap( stage, text, bundleIndex );

	/* Tell renderer to enable relief mapping since an heightmap is found
	also tell renderer to not abuse normalmap alpha channel because it's an heightmap.
	See https://github.com/DaemonEngine/Daemon/issues/183#issuecomment-473691252 */
	if ( stage->bundle[ bundleIndex ].image[ 0 ]->bits & IF_NORMALMAP
		&& stage->bundle[ bundleIndex ].image[ 0 ]->bits & IF_ALPHA )
	{
		Log::defaultLogger.DoDebugCode([&] {
			char buffer[ 1024 ];
			buffer[ 0 ] = '\0'
			bool parsed = ParseMap( &initialText, buffer, sizeof( buffer ) );
			ASSERT( parsed );
			Log::Debug("Found heightmap embedded in normalmap '%s'", buffer);
		});

		stage->isHeightMapInNormalMap = true;
	}
```

**Comment by illwieckz** [comment]
@slipher, I rewrote the things accordingly. I added a `UNUSED` keyword to silent the compiler complaining about `parsed` being unused on non-debug code. Or I may hack something like that instead:

```c
			#ifdef DEBUG
			bool parsed = 
			#endif
			ParseMap( &initialText, buffer, sizeof( buffer ) );
```

**Comment by slipher** [comment]
There is already a facility for marking an unused variable, `Q_UNUSED`. It's used like `Q_UNUSED(variable);`

Alternatively `if(!parsed) ASSERT(false);` would work.

**Comment by illwieckz** [comment]
Hmm, since all those tricks are there to move the `ParseMap` call out of `ASSERT`, then we can just avoid a `bool` and do:

```c
			if ( !ParseMap( &initialText, buffer, sizeof( buffer ) ) )
			{
				ASSERT( false );
			}
```

**Review by slipher — APPROVED** [review]

**Pull request merged**
