### PR TITLE
Use blackCube image instead of nothing for missing skybox image

### PR DESCRIPTION
**Pull request by slipher**
This can be seen on the Pulse map.

### CODE REVIEW

**Comment by slipher** [comment]
Turns out that setting the alpha to 255 (making the image be uploaded as RGB intead of transparent RGBA) was not really needed for this to work, since the sky shader is presumably always opaque. But it seems more correct anyway.

**Comment by illwieckz** [comment]
I guess you meant blackCube image?

**Comment by slipher** [comment]
Yeah it's a black image, not `blackImage` :stuck_out_tongue:

**Comment by illwieckz** [comment]
The PR title was confusing. 😄️

**Review by illwieckz — APPROVED** [review]
LGTM.

**Pull request merged**
