### PR TITLE
framework/CvarSystem: print when a cvar is modified

### PR DESCRIPTION
**Pull request by illwieckz**
It helped me to verify:

- #590

### CODE REVIEW

**Comment by slipher** [comment]
`modified` is a flag for legacy cvars which can be used to perform an action only when a cvar changes. Something like

```
// Change the fullscreen state only when the cvar changes
if (!r_fullscreen->modified)
    SetFullscreen(r_fullscreen->integer);
    r_fullscreen->modified = false;
}
```

Most cvars don't use this mechanism, so `modified` is always true for them.

What did you think the `modified` flag means?

**Comment by illwieckz** [comment]
> What did you think the `modified` flag means?

I was expecting to know if a cvar was modified. For example, is it equal to empty string because the user emptied it or because nothing was never written there.

**Comment by slipher** [comment]
> I was expecting to know if a cvar was modified.

You mean if it's not equal to the default value?

**Comment by illwieckz** [comment]
> You mean if it's not equal to the default value?

Yes, of course I can compare or make a `modified()` function for that.

**Comment by slipher** [comment]
The value and default value are shown, so it should be obvious whether they are not equal to each other. We don't need to print `modified` which would further increase the amount of text in some lines which are often very long.

**Pull request closed without merging**
