### PR TITLE
renderer: Remove unused r_drawSun cvar

### PR DESCRIPTION
**Pull request by DolceTriade**

### CODE REVIEW

**Review by necessarily-equal — APPROVED** [review]

**Comment by necessarily-equal** [comment]
there is a typo in the commit message, at "unused"

**Review by illwieckz — APPROVED** [review]
LGTM.

**Comment by illwieckz** [comment]
Like @necessarily-equal said, the `unsued` typo in commit message can be fixed but otherwise the patch itself is OK.

**Comment by DolceTriade** [comment]
Fixed typo in commit message. Will merge once it passes presubmits.

**Pull request merged**
