### PR TITLE
Fix fullscreen toggling bug (#365)

### PR DESCRIPTION
**Pull request by slipher**
This makes it possible to toggle r_fullscreen more than once without getting stuck.

Still want to look at a couple other things:

- Delete the code that makes (undesirable) changes to window cvars in response to SDL window resize events
- I noticed that toggling r_noBorder repeatedly causes a growing black space in the window.

### CODE REVIEW

**Comment by illwieckz** [comment]
I'm still experiencing issues, maybe differently.

I noticed that when I'm windowed after having been fullscreen, alt-tabbing out and in restore input, but alt-tabbing out and in does not restore input when I'm fullscreen after having been windowed.

I noticed I get this log everytime I go windowed from fullscreen:

```
The change to r_customwidth will take effect after restart. 
The change to r_customheight will take effect after restart. 
```

**Comment by illwieckz** [comment]
Note: My game height and width is not my desktop resolution. My desktop resolution is 4K and my game resolution is 2K. So when I go fullscreen, the game changes the desktop mode, and restore desktop mode when going windowed again.

**Comment by illwieckz** [comment]
I have some ideas for Dæmon/Unvanquished.

- having a window height / width different than fullscreen (which requires to call vid_restart when going windowed and back)
- leveraging the fake SDL fullscreen (fullscreen window atop everything)

But implementing those two features may hide the bug. So I want the bug to be fixed before someone investigate this.

I want you to know this because it may change the way your fixes are implemented. For example we can decide to drop classic fullscreen entirely or things like that. To be honest I've experienced no performance difference between windowed and classic fullscreen, even on 16 years old hardware. But I want to be sure we don't hide bugs because we delete a feature that uncovers it.

See https://wiki.libsdl.org/SDL_SetWindowFullscreen and `SDL_WINDOW_FULLSCREEN_DESKTOP`.

**Comment by slipher** [comment]
> alt-tabbing out and in does not restore input when I'm fullscreen after having been windowed.

Oh. Alt-Tab has always worked on Windows, so when you said this in the bug I assumed it was a typo for Alt-Enter (which toggles r_fullscreen).

> I noticed I get this log everytime I go windowed from fullscreen:

Yes, this is the first bullet point in the first post.

> My desktop resolution is 4K and my game resolution is 2K. So when I go fullscreen, I imagine the game changes the desktop mode
It does not. The resolution cannot be changed without a restart. So it can only stretch or truncate when changing size.

**Comment by slipher** [comment]
How about this for Alt+Enter (which currently just toggles r_fullscreen):

- If r_fullscreen is toggled to 1, set r_mode to -2 and vid_restart.
- If r_fullscreen is toggled to 0, set r_mode to -1, vid_restart and use the previously stored value of r_customwidth/height. If there is no previous value we could use half the screen dimensions.

**Comment by illwieckz** [comment]
To me dealing with things like that is for after 0.52, but we need input fixed for 0.52. I have many ideas about user experience that would decide the implementations, but I don't focus on them for the moment.

Can you remind me what does `r_mode -2`?

**Comment by slipher** [comment]
r_mode -2 makes the resolution the same as the screen resolution. It is the default.

**Comment by illwieckz** [comment]
Oh, so no, we really have to keep the ability to go fullscreen with a smaller resolution, this is one of the first need for full screen along with displaying nothing else on screen. For example people may play the game in 2K in full screen on a 4K screen to get higher framerate or enhanced graphical effects if their GPU don't keep up.

**Comment by illwieckz** [comment]
So, to return to the topic: yes, there was three bugs (at least on Linux with GNOME Shell):

- input is lost when going from fullscreen to window (or back) [usually with Alt+Enter],
- input is lost when switching between apps when the game is fullscreen [usually with Alt+Tab],
- input is lost when the game is entering map after the map load while the window is not focused.

Alt-tabbing with windowed game does not lose input. but having the game windowed and not in focus while loading the map will make the game loses input.

There is some interesting combinations, with this PR, if I go from fullscreen to window (with [Alt+Enter]) I lose input. But if I cycle between windows and come back to the windowed game (with [Alt+Tab]), I recover input.

But if go from window to fullscreen (with [Alt+Enter]), I cannot recover input, and if I cycle between windows, instead of recovering input all I got is a painted desktop pointer painted over the screen (which I can control instead of the game itself):

[fullscreen window lost input](https://dl.illwieckz.net/b/daemon/bugs/fullscreen-window-lost-input/20201006-214546-000.unvanquished-fullscreen-window-lost-input.png)

It looks like your PR fixes the third point (input is lost when the game is entering map after the map load while the window is not focused).

**Comment by illwieckz** [comment]
While running code from your PR, I noticed than when I cycle between windowed and fullscreen using [Alt+Enter], I can recover input by cycling between game and in game UI, for example when being spectator, clicking to open the team selection menu and pressing [Escape] to close that menu recovers input. If I'm already in a team, pressing [Escape] to display the main menu and [Escape] again to hide it recovers input.

Those tweaks do not work at all when input is lost when cycling between windows with [Alt+Tab].

**Comment by slipher** [comment]
I fixed the thing that sets cvars when you toggle r_fullscreen. I'm happy enough with how it works now on my own machine. Later I'll try it in a Linux VM.

**Comment by illwieckz** [comment]
So, to sum up the current status:

- input is lost when going from fullscreen to window (or back) [usually with Alt+Enter],
→ half fixed (display/hide UI trick required)
- input is lost when cycling between apps when the game is fullscreen [usually with Alt+Tab],
→ still broken
- input is lost when the game enters map after map load while the window is not focused.
→ fixed

I also noticed that the game frequently resets my custom height / width to my screen size on startup. It seems to be related to the fact I've cycled between windowed and fullscreen mode on the last run. Maybe this bug was introduced with that PR.

Note that I'm using GNOME Shell on Xorg on Ubuntu 20.04. I guess there is no need to get a real GPU in a virtual machine, llvmpipe-based OpenGL may be enough to reproduce the big.

**Comment by illwieckz** [comment]
Hmmm, I managed to load the game with a map on command line with a “fullscreen” game being minimized, and I cannot move the mouse. It's probably just the [Alt-Tab] bug, but it's interesting to notice I did not switched to any other window first, game started on fullscreen, but minimized.

About the current status of input issue, it looks like keyboard keys work, mouse button work, it's the mouse movement that is not captured, only that.

**Comment by slipher** [comment]
I did a lot of Alt+Enter, Alt+Tab and `vid_restart` on this branch in a Debian bullseye VM with GNOME desktop, but nothing bad happened. I also tried starting a devmap while minimized. How exactly do you produce bugs?

> I also noticed that the game frequently resets my custom height / width to my screen size on startup.

This PR should fix that, as long as you have `r_allowResize` at the default of 0.

**Comment by illwieckz** [comment]
> How exactly do you produce bugs?

Exactly the same way you attempted to: Alt+Enter, Alt+Tab and `vid_restart`… :confused: 

I'm using Ubuntu 20.04 with GNOME Shell…

> > I also noticed that the game frequently resets my custom height / width to my screen size on startup.
> This PR should fix that, as long as you have r_allowResize at the default of 0.

I experiment the opposite, I started to experiment that bug starting with this PR. Also `r_allowResize` is `0` on my end.

To reproduce it I can do this way:

- start the game windowed with a resolution smaller than the screen itself (for example 2k resolution on 4k screen), typically the config comes from a previous run
- switch to fullscreen with Alt+Enter (original resolution seems to be kept)
- return to windowed mode with Alt+Enter (original resolution is kept)
- quit the game
- restart the game

The game starts windowed but with fullscreen resolution.

**Comment by slipher** [comment]
Are you sure you are testing with the right code? I pushed the `r_allowResize`-related commit later than the other ones.

**Comment by illwieckz** [comment]
Hmm, I already knew GitHub does nasty things with commit ordering etc. but well, I missed two commits. I don't know yet for that resize issue, but input issue is still there. I just started the game both on background and fullscreen, I had no input in game when I alt-tabbed to display the game (UI trick did not recovered it). When I went windowed with Alt+Enter I had input in window mode, when I went fullscreen again I lost input (but UI trick recovered it). I Alt-Tabbed in and out and then lost input again (without being to recover it with UI trick). This was a brand new profile.

**Comment by illwieckz** [comment]
Note: I use GNOME Shell with Xorg, not Wayland, maybe there is a difference between both?

**Comment by slipher** [comment]
I tried with X instead of Wayland, but didn't managed to reproduce your bugs.

I did find one other way for r_custom* to get changed. If you set r_mode to something other than -1 (are you doing that?), then the engine sets r_custom* get set to whatever the actual resolution is. The way this is done now is a bit buggy as the currently used resolution is displayed as the "latched value", even though it is already in effect. I'm not sure what the best behavior is for when you use an r_mode not equal to -1:

1. Set r_custom* in a way that overrides CVAR_LATCH to be immediately displayed as the current value. This might be preferred so that the user can always inspect the current resolution by looking at the cvars.
2. Do not set r_custom*. This might be preferred so that the windowed resolution can be "remembered" while you are using `r_mode -2`.
3. Set the current value of the cvars to the current resolution, and the latched value to whatever the user manually set last. This is an attempt to get the best of both worlds.

I also found one other input bug. If I alt-tab out during a restart and alt-tab in after it finishes, I get an unwanted system cursor displayed (in addition to the librocket one). This condition can be cleared by cycling alt-tab again.

**Comment by slipher** [comment]
I implemented option (1) from the previous comment.

It would be interesting to see if any remaining bugs are improved by the SDL update in #401.

**Comment by illwieckz** [comment]
I get the exact same behaviour with #401 alone and #410 plus this one. Most of the time the only issue is the one when I have to click to recover input (that is less bad than before).

But while toying with a fresh profile, I reproduced the bug of I losing mouse input entirely and having my desktop mouse move over the game window… :-/

Anyway you can merge both PR as they are both steps forward, maybe rename this one to “Fix some fullscreen toggling bugs” because there may still be dragons, harder to find though.

**Comment by illwieckz** [comment]
Uh, forget what I said about “harder to find”, it's still really easy to reproduce that issue on my end, fresh or non-fresh profile, I just have to Alt-Tab from fullscreen then Alt-Tab back.

**Pull request merged**
