### PR TITLE
Allow disabling entity baselines (can load big layouts)

### PR DESCRIPTION
**Pull request by slipher**
Entity baselines are supposed to make netcode more efficient, but it's dubious (see #1321). Let server owners disable entity baselines with `set sv_useBaseline 0` as a workaround to https://github.com/Unvanquished/Unvanquished/issues/2124. This is compatible with vanilla clients. Probably no one will notice a difference wrt bandwith efficiency.

### CODE REVIEW

**Review by DolceTriade — COMMENTED** [review]
Seems like this would be more visible with high ping clients then?

**Comment by slipher** [comment]
Yes, high ping would make there be more of a difference. I imagine that it's even more important to have a room with a lot of entities in it, so that there are enough packets to congest the network. (And the entities should have existed since the server started, so that the baseline is helpful).

**Comment by slipher** [comment]
Server owners may use this if they want to load layouts with more than 600 or so buildables. But they should make sure the buildables are spread out somewhat. If you have hundreds of them in one room, clients will get lag spikes when the buildables enter PVS. The baseline does provide some advantage in the case that you have hundreds of entities in one place and those entities were present when the map loaded.

**Comment by slipher** [comment]
Added latch flag so that it is more obvious that you need to change map for a change to take effect.

**Comment by DolceTriade** [comment]
I feel like this is too big a change to add at the last minute. We can merge this after. Server hosts can cherry-pick this change in themselves if they need it since it's not compat breaking.

**Comment by slipher** [comment]
In what sense is it a big change? The diff is +11/-4 and it doesn't change anything unless you set the cvar.

**Comment by DolceTriade** [comment]
I mean it has the possibility to be an impactful change if there ends up being a regression. This is a nice to have thing with potential drawbacks. I don't think we need to force it in at the last minute.

**Comment by slipher** [comment]
I'm confused. Are you talking about the possibility of a regression if the user flips the cvar? Or the possibility of a regression if it is left unchanged?

**Comment by DolceTriade** [comment]
A regression if unchanged. As I said, if we wanted this merged, we should have done it sooner. This is not a required change and we've already shipped RC2. Let's ship 0.55 and we can merge this. If people want this, they can build it into their own servers.

**Comment by slipher** [comment]
Is this OK to merge now?

**Review by illwieckz — APPROVED** [review]
LGTM.

**Pull request merged**
