### PR TITLE
Fix GL_ARB_bindless_texture not being loaded on non-Mesa drivers

### PR DESCRIPTION
**Pull request by VReaperV**

### CODE REVIEW

**Comment by illwieckz** [comment]
That would have conflicted with https://github.com/DaemonEngine/Daemon/pull/1335

But since that was not the only mistake, I also implemented the bindless enablement fix in #1335 and fixed the other similar mistake.

**Comment by VReaperV** [comment]
So this is to be considered obsolete then?

**Comment by illwieckz** [comment]
yes, it is now meant to be obsoleted by #1335

**Comment by VReaperV** [comment]
Okay, closing this then.

**Pull request closed without merging**
