### PR TITLE
tty: Do not use nonblocking stdin 

### PR DESCRIPTION
**Pull request by DolceTriade**
This is buggy because if the engine is launched from a shell,
stdin will be shared and if anything on the shell (like gdb)
changes the stdin status, then unvanquished will also block.
Instead use select to determine if there is input ready to
be read. I didn't not notice any performance impact from this
change.

### CODE REVIEW

**Comment by DolceTriade** [comment]
Pretty sure this is wrong.

**Comment by illwieckz** [comment]
what's the status on this?

**Comment by DolceTriade** [comment]
It's still wrong and there is no good fix.

**Comment by illwieckz** [comment]
is there any hope to be able to run dæmon on gdb again one day (even with dirty solutions)?

**Comment by DolceTriade** [comment]
Run it with ncurses lol

**Comment by illwieckz** [comment]
Oh thank you! That's ugly because gdb messes with the curses output, but it works :+1:

But why it suddenly stopped to work?

**Comment by illwieckz** [comment]
Is there a way to entirely disable input for such case? there is still in game console and `daemon-tty`…

**Comment by DolceTriade** [comment]
Maybe we can disable tty. I'm not sure if there is a flag to disable it.

**Pull request closed without merging**
