### PR TITLE
Fix download with backup URL

### PR DESCRIPTION
**Pull request by slipher**
Fixes https://github.com/Unvanquished/Unvanquished/issues/1445

### CODE REVIEW

**Comment by illwieckz** [comment]
What is the underlying bug?

**Comment by slipher** [comment]
The code sending the backup URL was not updated to the new protocol which supports PAKSERVER checks.

**Comment by illwieckz** [comment]
Ah, that's not good then… What is the commented out `resetconfig`?

**Comment by slipher** [comment]
It's a convention for writing the names of unused arguments. To help the reader know what the argument is intended for, without triggering the unused variable warning.

**Comment by illwieckz** [comment]
If it works, LGTM.

**Pull request merged**
