### PR TITLE
Make NACL_VMS_PROJECTS accessible to outer scope

### PR DESCRIPTION
**Pull request by slipher**
Also remove duplicative nacl-vms-pexe target.

### CODE REVIEW

**Comment by illwieckz** [comment]
With that patch re-adding the separate generic `nacl-vms` target and toolchain-specific `nacl-vms-pexe` target, LGTM.

**Comment by illwieckz** [comment]
And actually I like the fact the `nacl-vms` target just exists to depend on the toolchain-specific targets anyway.

**Comment by slipher** [comment]
> Not removing the duplicative nacl-vms-pexe target fixes [Unvanquished/Unvanquished#3245 (comment)](https://github.com/Unvanquished/Unvanquished/pull/3245#issuecomment-2546433433)

Fixed. The Saigo-specific line creating a dummy target was mistakenly not in its `if` block.

**Comment by illwieckz** [comment]
It works, you can merge it, but I will add a generic `vms` target that is independent to the underlying format and toolchain anyway.

**Pull request merged**
