### PR TITLE
cg_api: Remove RmlUi defines from the engine

### PR DESCRIPTION
**Pull request by DolceTriade**
These are legacy defines from the days of having libRocket in the
engine. Now that RmlUI is built into the cgame, they don't need to be
here and should be in the cgame.

### CODE REVIEW

**Comment by illwieckz** [comment]
Fix https://github.com/Unvanquished/Unvanquished/issues/2052

@DolceTriade there is also this leftover (not rocket, but can be pruned at the same time):

> Another one like that is entityType_t in q_shared.h

**Comment by DolceTriade** [comment]
I'm not sure if we can remove entityType_t from the engine. entityState_t depends on entityType_t. I don't want to block merging this on cleaning up the entityType stuff though.

**Comment by illwieckz** [comment]
Sure, if it does not looks obvious on first sight, we can postpone. This will be good enough.

**Review by illwieckz — APPROVED** [review]
LGTM.

**Pull request merged**
