### PR TITLE
tr_init: r_novis should be latched

### PR DESCRIPTION
**Pull request by illwieckz**
`r_novis` should be latched

### CODE REVIEW

**Comment by slipher** [comment]
Why? It doesn't appear to be used during loading.

**Comment by illwieckz** [comment]
Well, I only get tris being drawn from “invisible parts” after a `vid_restart`.

**Comment by slipher** [comment]
Seems it's a little bit persistent between frames as long as you stay in one spot. You have to go to a different room for it to start working.

**Comment by illwieckz** [comment]
Ok then, that was a bit surprising, but it looks like moving around makes the tris updating according to vis and novis, one has to actually quit rooms and re-enters to see any difference.

**Pull request closed without merging**
