### PR TITLE
Fix nettle build issues yet again

### PR DESCRIPTION
**Pull request by slipher**

### CODE REVIEW

**Comment by DolceTriade** [comment]
CMakeFiles/engine-lib.dir/src/engine/framework/Crypto.cpp.o -c ../src/engine/framework/Crypto.cpp
../src/engine/framework/Crypto.cpp:36:28: fatal error: nettle/version.h: No such file or directory
 #include <nettle/version.h>

**Comment by illwieckz** [comment]
> the last attempt to make it work

(ヘ･_･)ヘ┳━┳

┳━┳ヘ(°□ °`)ヘ

ヘ('ಸ_ಸ)ヘ┳━┳

┳━┳＼(՞▃՞ ＼)

(╯°□°）╯︵ ┻━┻

**Comment by slipher** [comment]
Should we not drop 2.x then? How old of a version does it have?

**Comment by DolceTriade** [comment]
I'm happy as long as travis builds.

**Comment by slipher** [comment]
On ubuntu 14 there is only 2.7.

**Comment by DolceTriade** [comment]
We can probably add a PPA or something with something more recent. I'll try to find time to do this... (along with the repeater thing)

**Pull request merged**
