### PR TITLE
renderer: reusable SetRgbaGen

### PR DESCRIPTION
**Pull request by illwieckz**
Exported from:

- https://github.com/DaemonEngine/Daemon/pull/1075

This can be merged separately.

### CODE REVIEW

**Comment by slipher** [comment]
What does "Rrgba" mean?

**Comment by illwieckz** [comment]
> What does "Rrgba" mean?

The best typo in my life! 🤣️

At least the branch name doesn't have this typo… 🤦‍♀️️

…now fixed.

**Comment by illwieckz** [comment]
I also added some constness.

**Comment by slipher** [comment]
LGTM

**Pull request merged**
